# Generated by Django 3.2.18 on 2023-04-02 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_auto_20230402_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
