# Generated by Django 3.2.18 on 2023-04-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0005_despesa_data_despesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='data_despesa',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='despesa_paga',
            new_name='paga',
        ),
    ]
